DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id BIGINT(20) NOT NULL COMMENT '主键ID',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    age INT(11) NULL DEFAULT NULL COMMENT '年龄',
    email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    contact_number VARCHAR(50) NULL DEFAULT NULL COMMENT '联系电话',
    password VARCHAR(50) NULL DEFAULT NULL COMMENT '密码',
    sex INT(2) NULL DEFAULT NULL COMMENT '性别',
    PRIMARY KEY (id)
);
